from django.contrib import admin
from kiramama_app.models import *



admin.site.register(CHW)
admin.site.register(Mother)
admin.site.register(Report)
admin.site.register(RiskLevel)
admin.site.register(Lieu)
admin.site.register(CPN)
admin.site.register(BreastFeed)
admin.site.register(CON)
admin.site.register(ChildNumber)
admin.site.register(Gender)
admin.site.register(VAC)
admin.site.register(Symptom)
admin.site.register(DeathCode)
admin.site.register(HealthState)
admin.site.register(Rescue)
admin.site.register(ReportGRO)
admin.site.register(ReportCPN)
admin.site.register(ReportNSC)
admin.site.register(ReportCON)
admin.site.register(ReportVAC)
admin.site.register(ReportRIS)
admin.site.register(ReportRISBebe)
admin.site.register(ReportRER)
admin.site.register(ReportDEC)
admin.site.register(ReportDECBebe)
admin.site.register(ReportDEP)
admin.site.register(CONSymptom)
admin.site.register(CON_Report_Symptom)
admin.site.register(RIS_Report_Symptom)
