# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("kiramama_app", "0002_temporary")]

    operations = [
        migrations.AlterField(
            model_name="reportnsc",
            name="breast_feading",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kiramama_app.BreastFeed",
            ),
        )
    ]
