# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiramama_app', '0003_auto_20160829_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportnsc',
            name='child_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiramama_app.ChildNumber'),
        ),
        migrations.AlterField(
            model_name='reportnsc',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiramama_app.Gender'),
        ),
    ]
