# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-06 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiramama_app', '0004_auto_20160829_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='con_report_symptom',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiramama_app.Symptom'),
        ),
        migrations.AlterField(
            model_name='ris_report_symptom',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiramama_app.Symptom'),
        ),
        migrations.DeleteModel(
            name='CONSymptom',
        ),
        migrations.DeleteModel(
            name='RISSymptom',
        ),
    ]
