# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiramama_app', '0005_auto_20160906_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthState',
            new_name='HealthStatus',
        ),
        migrations.RenameField(
            model_name='healthstatus',
            old_name='health_state_code_meaning',
            new_name='health_status_code_meaning',
        ),
        migrations.RenameField(
            model_name='healthstatus',
            old_name='health_state_desigantion',
            new_name='health_status_desigantion',
        ),
    ]
