# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("kiramama_app", "0006_auto_20160914_1533")]

    operations = [
        migrations.CreateModel(
            name="NotificationsCHW",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "chw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kiramama_app.CHW",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationsForCHW",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_to_send", models.CharField(max_length=160)),
                ("time_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationsForMother",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_to_send", models.CharField(max_length=160)),
                ("time_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationsMother",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kiramama_app.Mother",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kiramama_app.NotificationsForMother",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TimeMeasuringUnit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=4)),
                ("description", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="notificationsformother",
            name="notification_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kiramama_app.NotificationType",
            ),
        ),
        migrations.AddField(
            model_name="notificationsformother",
            name="time_measuring_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kiramama_app.TimeMeasuringUnit",
            ),
        ),
        migrations.AddField(
            model_name="notificationsforchw",
            name="notification_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kiramama_app.NotificationType",
            ),
        ),
        migrations.AddField(
            model_name="notificationsforchw",
            name="time_measuring_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kiramama_app.TimeMeasuringUnit",
            ),
        ),
        migrations.AddField(
            model_name="notificationschw",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="kiramama_app.NotificationsForCHW",
            ),
        ),
    ]
