# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-06 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiramama_app', '0007_auto_20161103_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsforchw',
            name='word_to_replace_by_the_date_in_the_message_to_send',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationsforchw',
            name='word_to_replace_by_the_mother_id_in_the_message_to_send',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationsformother',
            name='word_to_replace_by_the_date_in_the_message_to_send',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
