# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-24 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiramama_app', '0009_auto_20161106_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationschw',
            name='message_to_send',
            field=models.CharField(default='!', max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationsmother',
            name='message_to_send',
            field=models.CharField(default='1', max_length=160),
            preserve_default=False,
        ),
    ]
