# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-18 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiramama_app', '0010_auto_20161124_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportREC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiramama_app.Report')),
            ],
        ),
    ]
