# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-14 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kiramama_app", "0018_chw_reg_date")]

    operations = [
        migrations.AddField(
            model_name="cpn",
            name="cpn_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        )
    ]
