# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-24 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiramama_app', '0019_cpn_cpn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpn',
            name='cpn_number',
            field=models.IntegerField(unique=True),
        ),
    ]
