# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-04 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kiramama_app", "0020_auto_20170724_1241")]

    operations = [
        migrations.AddField(
            model_name="symptom",
            name="is_red_symptom",
            field=models.BooleanField(default=False),
        )
    ]
