# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-11 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kiramama_app", "0022_allsupervisor_districtsupervisor")]

    operations = [
        migrations.AddField(
            model_name="symptom",
            name="kirundi_name",
            field=models.CharField(default="", max_length=50),
        )
    ]
