# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-10-19 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_administration_structure_app', '0006_merge'),
        ('kiramama_app', '0030_bpssupervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDSSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_administration_structure_app.CDS')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiramama_app.AllSupervisor')),
            ],
        ),
    ]
