# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-20 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_administration_structure_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
