# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-27 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("health_administration_structure_app", "0004_auto_20170223_1051")]

    operations = [
        migrations.AlterField(
            model_name="cds", name="name", field=models.CharField(max_length=100)
        )
    ]
