# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-24 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_administration_structure_app', '0005_auto_20170227_1234'),
        ('health_administration_structure_app', '0002_auto_20170220_1127'),
    ]

    operations = [
    ]
